import { useState, useEffect } from "react"
import { useSearchParams } from "react-router-dom"
import Editor from "@monaco-editor/react"
import { Card } from "../components/ui/card"
import { Button } from "../components/ui/button"
import { Badge } from "../components/ui/badge"
import { Progress } from "../components/ui/progress"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "../components/ui/tabs"
import { api } from "../lib/api"
import { Sparkles, Download, Copy, Check, Loader2, Play, FileText, Database, Code, TestTube, Book } from "lucide-react"

const agentConfig: Record<string, { endpoint: string; icon: any; language: string; description: string }> = {
  Architecture: { endpoint: "/architecture", icon: Sparkles, language: "markdown", description: "System architecture design" },
  Database: { endpoint: "/database", icon: Database, language: "sql", description: "Database schema and migrations" },
  Apis: { endpoint: "/apis", icon: Code, language: "python", description: "REST API endpoints" },
  Frontend: { endpoint: "/frontend", icon: Code, language: "typescript", description: "React components and pages" },
  Backend: { endpoint: "/backend", icon: Code, language: "python", description: "FastAPI backend code" },
  Testing: { endpoint: "/tests", icon: TestTube, language: "python", description: "Test suites and coverage" },
  Documentation: { endpoint: "/docs", icon: Book, language: "markdown", description: "Comprehensive documentation" },
  Projects: { endpoint: "", icon: FileText, language: "json", description: "Project overview" },
  Settings: { endpoint: "", icon: Sparkles, language: "json", description: "Project settings" },
}

export function GeneratorPage({ title }: { title: string }) {
  const [searchParams] = useSearchParams()
  const projectId = searchParams.get("project")
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [progress, setProgress] = useState(0)
  const [content, setContent] = useState("")
  const [copied, setCopied] = useState(false)
  const [logs, setLogs] = useState<string[]>([])

  const config = agentConfig[title] || agentConfig.Architecture
  const Icon = config.icon

  useEffect(() => {
    if (projectId) {
      fetchArtifact()
    }
  }, [projectId, title])

  const fetchArtifact = async () => {
    if (!projectId || !config.endpoint) return
    setLoading(true)
    try {
      const kind = title.toLowerCase()
      const artifacts = await api<any[]>(`/projects/${projectId}/artifacts?kind=${kind}`)
      if (artifacts.length > 0) {
        setContent(artifacts[0].markdown || JSON.stringify(artifacts[0].content, null, 2))
      }
    } catch (error) {
      console.error("Failed to fetch artifact:", error)
    } finally {
      setLoading(false)
    }
  }

  const generate = async () => {
    if (!config.endpoint) return
    setGenerating(true)
    setProgress(0)
    setLogs([])
    setContent("")

    // Simulate progress
    const progressInterval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 90) {
          clearInterval(progressInterval)
          return 90
        }
        return prev + 10
      })
    }, 300)

    try {
      const result = await api<any>(config.endpoint, {
        method: "POST",
        body: JSON.stringify({ project_id: projectId, prompt: `Generate ${title}` }),
      })

      setLogs(result.logs || [])
      setProgress(100)

      // Save as artifact
      if (projectId) {
        const markdown = generateMarkdown(result.output, title)
        await api(`/projects/${projectId}/artifacts`, {
          method: "POST",
          body: JSON.stringify({
            kind: title.toLowerCase(),
            content: result.output,
            markdown,
          }),
        })
        setContent(markdown)
      } else {
        setContent(JSON.stringify(result.output, null, 2))
      }
    } catch (error) {
      console.error("Generation failed:", error)
      setLogs(["Generation failed. Please try again."])
    } finally {
      clearInterval(progressInterval)
      setGenerating(false)
    }
  }

  const generateMarkdown = (output: any, title: string) => {
    if (typeof output === "string") return output
    return `# ${title}

Generated by Sketch2Startup AI

\`\`\`json
${JSON.stringify(output, null, 2)}
\`\`\`
`
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadContent = () => {
    const extension = config.language === "typescript" ? "ts" : config.language
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${title.toLowerCase()}.${extension}`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-cyan-400" />
      </div>
    )
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">
            {title} Generator
          </h2>
          <p className="mt-1 text-slate-400">{config.description}</p>
        </div>
        <div className="flex gap-2">
          {content && (
            <>
              <Button variant="outline" onClick={copyToClipboard}>
                {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button variant="outline" onClick={downloadContent}>
                <Download className="h-4 w-4 mr-2" />
                Download
              </Button>
            </>
          )}
          {config.endpoint && (
            <Button
              className="bg-gradient-to-r from-violet-500 to-cyan-500 hover:from-violet-600 hover:to-cyan-600"
              onClick={generate}
              disabled={generating}
            >
              {generating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Play className="h-4 w-4 mr-2" />
                  Generate
                </>
              )}
            </Button>
          )}
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <Card className="border border-slate-700/50 bg-slate-800/30 backdrop-blur-sm p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-violet-500/20 to-cyan-500/20">
              <Icon className="h-5 w-5 text-cyan-400" />
            </div>
            <div>
              <h3 className="font-semibold text-slate-200">Agent Status</h3>
              <Badge variant={generating ? "secondary" : "outline"} className="mt-1">
                {generating ? "Running" : "Ready"}
              </Badge>
            </div>
          </div>

          {generating && (
            <div className="space-y-3">
              <Progress value={progress} className="h-2" />
              <p className="text-sm text-slate-400">{progress}% complete</p>
            </div>
          )}

          <div className="mt-4 space-y-2">
            <h4 className="text-sm font-medium text-slate-300">Agent Logs</h4>
            <div className="space-y-1 max-h-48 overflow-y-auto">
              {logs.length > 0 ? (
                logs.map((log, index) => (
                  <p key={index} className="text-xs text-slate-400 font-mono">
                    {log}
                  </p>
                ))
              ) : (
                <p className="text-xs text-slate-500">No logs yet</p>
              )}
            </div>
          </div>
        </Card>

        <Card className="lg:col-span-2 border border-slate-700/50 bg-slate-800/30 backdrop-blur-sm overflow-hidden">
          {content ? (
            <Editor
              height="500px"
              theme="vs-dark"
              defaultLanguage={config.language}
              value={content}
              onChange={(value) => setContent(value || "")}
              options={{
                minimap: { enabled: false },
                fontSize: 14,
                lineNumbers: "on",
                scrollBeyondLastLine: false,
                wordWrap: "on",
              }}
            />
          ) : (
            <div className="flex h-[500px] items-center justify-center">
              <div className="text-center space-y-4">
                <div className="flex h-16 w-16 items-center justify-center rounded-full bg-slate-800 mx-auto">
                  <Icon className="h-8 w-8 text-slate-600" />
                </div>
                <div className="space-y-2">
                  <p className="text-lg font-medium text-slate-200">No {title} Generated Yet</p>
                  <p className="text-sm text-slate-400">
                    Click the Generate button to create {title.toLowerCase()} using AI
                  </p>
                </div>
              </div>
            </div>
          )}
        </Card>
      </div>
    </div>
  )
}